import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const tag = process.argv[2];
assert.match(tag || '', /^v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/, 'Expected a vX.Y.Z release tag');
const version = readFileSync(new URL('../VERSION', import.meta.url), 'utf8').trim();
const pkg = JSON.parse(readFileSync(new URL('../web/package.json', import.meta.url), 'utf8'));
const lock = JSON.parse(readFileSync(new URL('../web/package-lock.json', import.meta.url), 'utf8'));
const changes = readFileSync(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
const openapi = readFileSync(new URL('../api/openapi.yaml', import.meta.url), 'utf8');
const sdk = JSON.parse(readFileSync(new URL('../packages/sdk/package.json', import.meta.url), 'utf8'));
const site = JSON.parse(readFileSync(new URL('../site/package.json', import.meta.url), 'utf8'));
const siteLock = JSON.parse(readFileSync(new URL('../site/package-lock.json', import.meta.url), 'utf8'));
assert.equal(tag, `v${version}`, 'Tag and VERSION must agree');
assert.equal(pkg.version, version, 'UI and VERSION must agree');
assert.equal(sdk.version, version, 'SDK and VERSION must agree');
assert.equal(site.version, version, 'Website and VERSION must agree');
assert.equal(siteLock.version, version, 'Website lockfile and VERSION must agree');
assert.equal(siteLock.packages[''].version, version, 'Website root lock entry must agree');
assert.equal(lock.version, version, 'Lockfile and VERSION must agree');
assert.equal(lock.packages[''].version, version, 'Root lock entry must agree');
assert.ok(changes.includes(`## [${version}]`), 'Release needs a CHANGELOG entry');
assert.equal(openapi.match(/^  version: (.+)$/m)?.[1], version, 'OpenAPI and VERSION must agree');
console.log(`Release metadata verified: ${tag}`);
