import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const tag = process.argv[2];
assert.match(tag || '', /^v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/, 'Expected a vX.Y.Z release tag');
const version = readFileSync(new URL('../VERSION', import.meta.url), 'utf8').trim();
const pkg = JSON.parse(readFileSync(new URL('../web/package.json', import.meta.url), 'utf8'));
const lock = JSON.parse(readFileSync(new URL('../web/package-lock.json', import.meta.url), 'utf8'));
const changes = readFileSync(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
const openapi = readFileSync(new URL('../api/openapi.yaml', import.meta.url), 'utf8');
const sdk = JSON.parse(readFileSync(new URL('../packages/sdk/package.json', import.meta.url), 'utf8'));
const site = JSON.parse(readFileSync(new URL('../site/package.json', import.meta.url), 'utf8'));
const siteLock = JSON.parse(readFileSync(new URL('../site/package-lock.json', import.meta.url), 'utf8'));
const android = readFileSync(new URL('../android/app/build.gradle', import.meta.url), 'utf8');
const androidSample = readFileSync(new URL('../android/otp-sample/build.gradle', import.meta.url), 'utf8');
const ios = readFileSync(new URL('../examples/ios-otp/project.yml', import.meta.url), 'utf8');
assert.equal(tag, `v${version}`, 'Tag and VERSION must agree');
assert.equal(pkg.version, version, 'UI and VERSION must agree');
assert.equal(sdk.version, version, 'SDK and VERSION must agree');
assert.equal(site.version, version, 'Website and VERSION must agree');
assert.equal(android.match(/versionName '([^']+)'/)?.[1], version, 'Android versionName and VERSION must agree');
const buildNumber = android.match(/versionCode (\d+)/)?.[1];
assert.match(buildNumber || '', /^[1-9]\d*$/, 'Native apps need a positive build number');
assert.equal(androidSample.match(/versionCode (\d+)/)?.[1], buildNumber, 'Android APK build numbers must agree');
assert.equal(ios.match(/CURRENT_PROJECT_VERSION: '(\d+)'/)?.[1], buildNumber, 'Native build numbers must agree');
assert.equal(ios.match(/MARKETING_VERSION: '([^']+)'/)?.[1], version.split('-')[0], 'iOS marketing version must match the release series');
assert.equal(siteLock.version, version, 'Website lockfile and VERSION must agree');
assert.equal(siteLock.packages[''].version, version, 'Website root lock entry must agree');
assert.equal(lock.version, version, 'Lockfile and VERSION must agree');
assert.equal(lock.packages[''].version, version, 'Root lock entry must agree');
assert.ok(changes.includes(`## [${version}]`), 'Release needs a CHANGELOG entry');
assert.equal(openapi.match(/^  version: (.+)$/m)?.[1], version, 'OpenAPI and VERSION must agree');
console.log(`Release metadata verified: ${tag}`);
